### ISSUE TITLE
IJulia is not starting julia 1.9 kernel

### ISSUE THREAD

**Issue by dove88** [JuliaLang/IJulia.jl#1076]
IJulia is not starting julia 1.9 kernel,
It works fine with 1.8 version

**Comment by bjarthur** [comment]
it could be that you need to `conda update nbconvert`

**Comment by stevengj** [comment]
Works for me.   I didn't update anything about conda.

See also the Debugging section of the manual: https://julialang.github.io/IJulia.jl/stable/manual/troubleshooting/#Debugging-IJulia-problems

**Comment by bjarthur** [comment]
when running remotely on a headless machine, i was getting `ImportError: cannot import name 'contextfilter' from 'jinja2'`.  upgrading nbconvert fixed it.

**Comment by dove88** [comment]
Thank you, actually i forgot to build the IJulia, it is working fine now...
